services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: p2p
      MYSQL_USER: p2p
      MYSQL_PASSWORD: p2p
      MYSQL_DATABASE: p2p
    ports:
      - '3306:3306'
    volumes:
      - p2p_mysql_data:/var/lib/mysql

volumes:
  p2p_mysql_data:
