services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: p2p
      POSTGRES_PASSWORD: p2p
      POSTGRES_DB: p2p
    ports:
      - '5432:5432'
    volumes:
      - p2p_postgres_data:/var/lib/postgresql/data

volumes:
  p2p_postgres_data:
